/* Automatically generated by './build/make/*.js' */
import { mapGetters, mapActions } from "vuex";
import store from "../_store/index.js";

export default {
  data: function() {
    return {};
  },
  methods: {
    ...mapActions({
      queryPunishList: store.namespace + "/queryPunishList3",

      getSchemeStateDict: store.namespace + "/getSchemeStateDict",
      querySchoolYearDict: store.namespace + "/querySchoolYearDict",
      getCurrentOrgListAndOwner: store.namespace + "/getCurrentOrgListAndOwner",
      updateScheme: store.namespace + "/updateScheme",

      insertScheme: store.namespace + "/insertScheme",

      copyScheme: store.namespace + "/copyScheme",

      processSchemeName: store.namespace + "/processSchemeName",

      deleteSchemeById: store.namespace + "/deleteSchemeById",

      startScheme: store.namespace + "/startScheme",

      getEvalItemBeanBySchemeId: store.namespace + "/getEvalItemBeanBySchemeId",

      saveExEveluateBean: store.namespace + "/saveExEveluateBean",

      queryExpandEvalCategory: store.namespace + "/queryExpandEvalCategory"
    })
  }
};
