/* Automatically generated by './build/make/*.js' */
import { mapGetters, mapActions } from "vuex";
import store from "../_store/index.js";

export default {
  data: function() {
    return {};
  },
  computed: {
    ...mapGetters({
      GET_expandCheckStateDict: store.namespace + "/GET_expandCheckStateDict",
      GET_DataSourceDict: store.namespace + "/GET_DataSourceDict",
      GET_DataSourceDictByValue: store.namespace + "/GET_DataSourceDictByValue"
    })
  },
  methods: {
    ...mapActions({
      getExpandEvalTemplateUrl: store.namespace + "/getExpandEvalTemplateUrl",
      queryPunishList: store.namespace + "/queryPunishList3",
      getSchemeStateDict: store.namespace + "/getSchemeStateDict",
      querySchoolYearDict: store.namespace + "/querySchoolYearDict",
      getCurrentOrgListAndOwner: store.namespace + "/getCurrentOrgListAndOwner",
      queryPunishItemByShoolYearId:
        store.namespace + "/queryPunishItemByShoolYearId",
      getSchemeStateDict: store.namespace + "/getSchemeStateDict",

      queryStudentBaseInfo: store.namespace + "/queryStudentBaseInfo",
      updateScheme: store.namespace + "/updateScheme",

      insertScheme: store.namespace + "/insertScheme",

      copyScheme: store.namespace + "/copyScheme",

      processSchemeName: store.namespace + "/processSchemeName",

      deleteSchemeById: store.namespace + "/deleteSchemeById",

      startScheme: store.namespace + "/startScheme",

      getEvalItemBeanBySchemeId: store.namespace + "/getEvalItemBeanBySchemeId",

      saveExEveluateBean: store.namespace + "/saveExEveluateBean",

      queryExpandEvalCategory: store.namespace + "/queryExpandEvalCategory",

      getExpandEvalCatagoryBySchoolYearId:
        store.namespace + "/getExpandEvalCatagoryBySchoolYearId",

      getExpandEvalCatagoryByDate:
        store.namespace + "/getExpandEvalCatagoryByDate",

      createExpandRecord: store.namespace + "/createExpandRecord",

      applyExpandRecord: store.namespace + "/applyExpandRecord",

      checkExpandRecord: store.namespace + "/checkExpandRecord",

      getExpandEvalRecordById: store.namespace + "/getExpandEvalRecordById",

      getExpandCheckStateDict: store.namespace + "/getExpandCheckStateDict",

      getDataSourceDict: store.namespace + "/getDataSourceDict",

      queryExpandEvalRecordForStaff:
        store.namespace + "/queryExpandEvalRecordForStaff",

      queryExpandEvalRecordForStu:
        store.namespace + "/queryExpandEvalRecordForStu",

      queryExpandEvalRecordForCheck:
        store.namespace + "/queryExpandEvalRecordForCheck",

      adStuExpandEval: store.namespace + "/adStuExpandEval",

      importExpandEvalRecord: store.namespace + "/importExpandEvalRecord"
    })
  }
};
