
/* Automatically generated by './build/make/*.js' */
import { mapGetters, mapActions } from "vuex";
import store from "../_store/index.js";

export default {
  data: function() {
    return {};
  },
  methods: {
    ...mapActions({
     
 getItemsTree: store.namespace + '/getItemsTree',

 processPunishName: store.namespace + '/processPunishName',

 insertScheme: store.namespace + '/insertScheme',

 copyScheme: store.namespace + '/copyScheme',

 deleteScheme: store.namespace + '/deleteScheme',

 querySchemeList: store.namespace + '/querySchemeList',

 savePunishItems: store.namespace + '/savePunishItems',

 saveEvalItems: store.namespace + '/saveEvalItems',

 saveCapacityItems: store.namespace + '/saveCapacityItems',

      getDictByDictNames: store.namespace + "/getDictByDictNames",
 saveInnovateItems: store.namespace + '/saveInnovateItems',

 getPunishItems: store.namespace + '/getPunishItems',

 getEvalItems: store.namespace + '/getEvalItems',

 getCapacityItems: store.namespace + '/getCapacityItems',

 getInnovateItems: store.namespace + '/getInnovateItems',
    })
  }
};

