/* Automatically generated by './build/make/*.js' */
import { mapGetters, mapActions } from "vuex";
import store from "../_store/index.js";

export default {
  data: function() {
    return {};
  },
  methods: {
    ...mapActions({
      getItemsTree: store.namespace + "/getItemsTree",

      processSchemeName: store.namespace + "/processSchemeName1",
      querySchoolYearDict: store.namespace + "/querySchoolYearDict",
      insertScheme: store.namespace + "/insertScheme1",

      copyScheme: store.namespace + "/copyScheme1",

      deleteScheme: store.namespace + "/deleteScheme1",
      updateScheme: store.namespace + "/updateScheme1",

      querySchemeList: store.namespace + "/querySchemeList",

      savePunishItems: store.namespace + "/savePunishItems",

      saveEvalItems: store.namespace + "/saveEvalItems",

      saveCapacityItems: store.namespace + "/saveCapacityItems",

      getDictByDictNames: store.namespace + "/getDictByDictNames",
      saveInnovateItems: store.namespace + "/saveInnovateItems",

      getPunishItems: store.namespace + "/getPunishItems",

      getEvalItems: store.namespace + "/getEvalItems",

      getCapacityItems: store.namespace + "/getCapacityItems",

      getInnovateItems: store.namespace + "/getInnovateItems"
    })
  }
};
