
/* Automatically generated by './build/make/*.js' */

export default {
  data: function() {
    return {};
  },
  methods: {
    ...mapActions({
     
 queryPunishList: store.namespace + '/queryPunishList',

 getPunishStateDict: store.namespace + '/getPunishStateDict',

 getPunishItemStateDict: store.namespace + '/getPunishItemStateDict',

 updatePunish: store.namespace + '/updatePunish',

 insertPunish: store.namespace + '/insertPunish',

 copyPunish: store.namespace + '/copyPunish',

 processPunishName: store.namespace + '/processPunishName',

 deletePunishById: store.namespace + '/deletePunishById',

 startPunish: store.namespace + '/startPunish',

 getPunishItemBeanByPunishId: store.namespace + '/getPunishItemBeanByPunishId',

 savePunishItemBean: store.namespace + '/savePunishItemBean',

 queryPunishItemByShoolYearId: store.namespace + '/queryPunishItemByShoolYearId',

 queryPunishRecordForStaff: store.namespace + '/queryPunishRecordForStaff',

 queryPunishRecordForStu: store.namespace + '/queryPunishRecordForStu',

 insertPunishRecord: store.namespace + '/insertPunishRecord',

 deletePunishRecord: store.namespace + '/deletePunishRecord',

 getPunshiRecordById: store.namespace + '/getPunshiRecordById',

 oadStuPunish: store.namespace + '/oadStuPunish',

 importPunishRecord: store.namespace + '/importPunishRecord',
    })
  }
};

