/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";
//查询学年列表(下拉框)
const querySchoolYearDict = data =>
  request({
    url: "/schoolYear/querySchoolYearDict.do",
    method: "post",
    data: data
  });
const queryMajorList = data =>
  request({
    url: "/dOrg/queryMajorList.do",
    method: "post",
    data: data
  });

const insertOrg = data =>
  ajax({
    url: "/dOrg/insertOrg.do",
    method: "post",
    data: data
  });

const getOrgTreeView = data =>
  request({
    url: "/dOrg/getOrgTreeView.do",
    method: "post",
    data: data
  });

const updateOrg = data =>
  ajax({
    url: "/dOrg/updateOrg.do",
    method: "post",
    data: data
  });

const deleteOrg = data =>
  request({
    url: "/dOrg/deleteOrg.do",
    method: "post",
    data: data
  });

const getOrg = data =>
  request({
    url: "/dOrg/getOrg.do",
    method: "post",
    data: data
  });

const getDictByDictNames = data =>
  request({
    url: "/systemConfApi/getDictByDictNames.do",
    method: "post",
    data: data
  });
export default {
  querySchoolYearDict,
  queryMajorList,
  insertOrg,
  getOrgTreeView,
  updateOrg,
  deleteOrg,
  getOrg,
  getDictByDictNames
};
