/* Automatically generated by './build/make/*.js' */

import api from "../../_api/appraisalConfig";

const getAppraiseAllowConfigTime = ({ commit, state }, params) =>
    new Promise(resolve => {
        api.getAppraiseAllowConfigTime(params).then(response => {
            resolve(response);
        });
    });
const saveAppraisalAllowConfigTime = ({ commit, state }, params) =>
    new Promise(resolve => {
        api.saveAppraisalAllowConfigTime(params).then(response => {
            resolve(response);
        });
    });


export default {
    getAppraiseAllowConfigTime,
    saveAppraisalAllowConfigTime
};
