/* Automatically generated by './build/make/*.js' */

import api from "../../_api/menus.js";
const querySchoolYearDict = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.querySchoolYearDict(params).then(response => {
      resolve(response);
    });
  });
const queryMajorList = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.queryMajorList(params).then(response => {
      resolve(response);
    });
  });

const insertOrg = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.insertOrg(params).then(response => {
      resolve(response);
    });
  });

const getOrgTreeView = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.getOrgTreeView(params).then(response => {
      resolve(response);
    });
  });

const updateOrg = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.updateOrg(params).then(response => {
      resolve(response);
    });
  });

const deleteOrg = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.deleteOrg(params).then(response => {
      resolve(response);
    });
  });

const getOrg = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.getOrg(params).then(response => {
      resolve(response);
    });
  });

const getDictByDictNames = ({ commit, state }, params) =>
  new Promise(resolve => {
    api.getDictByDictNames(params).then(response => {
      resolve(response);
    });
  });
export default {
  querySchoolYearDict,
  queryMajorList,
  insertOrg,
  getOrgTreeView,
  updateOrg,
  deleteOrg,
  getOrg,
  getDictByDictNames
};
