export const dispenseView = {
  scope: {
    id: '',
    scopeKey: '',
    scopeName: '',
    serviceOrderNo: '',
    serviceType: '',
    orgCode: '',
    orgName: '',
    liablerId: '',
    isRootScope: '',
    isLeafScope: '',
    planStartTime: '',
    planEndTime: '',
    planTimeLong: '',
    realStartTime: '',
    realEndTime: '',
    delayEndTime: '',
    delayTimeLong: '',
    isActive: '',
    createor: '',
    createTime: '',
    deployKey: '',
    scopeState: '',
    parentId: '',
    relaseItemId: ''
  },
  deployPack: {
    nameSpace: '',
    scope: '',
    name: '',
    isRoot: '',
    isLeaf: '',
    scopeDataRule: '',
    rule: '',
    ruleEditable: '',
    childScopePackage: '',
    firstItem: '',
    lastItem: '',
    itemMap: '',
    items: '',
    groups: '',
    liaRuleMap: '',
    parRuleMap: '',
    variableMap: '',
    timeLongRelase: '',
    linkedItems: ''
  },
  relaseTimeDay: 0,
  oldRelaseTimeDay: 365 * 10,
  relaseTimeLong: 0,
  setOldRelaseTimeLong: 65535,
  relaseWorkItemName: null
}
