/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";

const queryPunishList = data =>
  request({
    url: "/baseQuality/queryPunishList.do",
    method: "post",
    data: data
  });

const getPunishStateDict = data =>
  request({
    url: "/baseQuality/getPunishStateDict.do",
    method: "post",
    data: data
  });

const updateScheme = data =>
  request({
    url: "/baseQuality/updateScheme.do",
    method: "post",
    data: data
  });

const insertScheme = data =>
  request({
    url: "/baseQuality/insertScheme.do",
    method: "post",
    data: data
  });

const copyScheme = data =>
  request({
    url: "/baseQuality/copyScheme.do",
    method: "post",
    data: data
  });

const processSchemeName = data =>
  request({
    url: "/baseQuality/processSchemeName.do",
    method: "post",
    data: data
  });

const deleteSchemeById = data =>
  request({
    url: "/baseQuality/deleteSchemeById.do",
    method: "post",
    data: data
  });

const startScheme = data =>
  request({
    url: "/baseQuality/startScheme.do",
    method: "post",
    data: data
  });

const getBaseQualtityItemBeanBySchemeId = data =>
  request({
    url: "/baseQuality/getBaseQualtityItemBeanBySchemeId.do",
    method: "post",
    data: data
  });

const saveBaseQualtityItemBean = data =>
  ajax({
    url: "/baseQuality/saveBaseQualtityItemBean.do",
    method: "post",
    data: data
  });

const queryBaseQualtityCategory = data =>
  request({
    url: "/baseQuality/queryBaseQualtityCategory.do",
    method: "post",
    data: data
  });

const queryEvalList = data =>
  request({
    url: "/baseQuality/queryEvalList.do",
    method: "post",
    data: data
  });

const queryEvalListForStu = data =>
  request({
    url: "/baseQuality/queryEvalListForStu.do",
    method: "post",
    data: data
  });


export default {
  queryEvalListForStu,
  queryPunishList,
  getPunishStateDict,
  updateScheme,
  insertScheme,
  copyScheme,
  processSchemeName,
  deleteSchemeById,
  startScheme,
  getBaseQualtityItemBeanBySchemeId,
  saveBaseQualtityItemBean,
  queryBaseQualtityCategory,
  queryEvalList
};
