/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";

const queryPunishList = data =>
  request({
    url: "/seQuality/queryPunishList.do",
    method: "post",
    data: data
  });

const getPunishStateDict = data =>
  request({
    url: "/seQuality/getPunishStateDict.do",
    method: "post",
    data: data
  });

const updateScheme = data =>
  request({
    url: "/seQuality/updateScheme.do",
    method: "post",
    data: data
  });

const insertScheme = data =>
  request({
    url: "/seQuality/insertScheme.do",
    method: "post",
    data: data
  });

const copyScheme = data =>
  request({
    url: "/seQuality/copyScheme.do",
    method: "post",
    data: data
  });

const processSchemeName = data =>
  request({
    url: "/seQuality/processSchemeName.do",
    method: "post",
    data: data
  });

const deleteSchemeById = data =>
  request({
    url: "/seQuality/deleteSchemeById.do",
    method: "post",
    data: data
  });

const startScheme = data =>
  request({
    url: "/seQuality/startScheme.do",
    method: "post",
    data: data
  });

const getBaseQualtityItemBeanBySchemeId = data =>
  request({
    url: "/seQuality/getBaseQualtityItemBeanBySchemeId.do",
    method: "post",
    data: data
  });

const saveBaseQualtityItemBean = data =>
  request({
    url: "/seQuality/saveBaseQualtityItemBean.do(json请求)",
    method: "post",
    data: data
  });

const queryBaseQualtityCategory = data =>
  request({
    url: "/seQuality/queryBaseQualtityCategory.do",
    method: "post",
    data: data
  });

const queryEvalList = data =>
  request({
    url: "/seQuality/queryEvalList.do",
    method: "post",
    data: data
  });
export default {
  queryPunishList,
  getPunishStateDict,
  updateScheme,
  insertScheme,
  copyScheme,
  processSchemeName,
  deleteSchemeById,
  startScheme,
  getBaseQualtityItemBeanBySchemeId,
  saveBaseQualtityItemBean,
  queryBaseQualtityCategory,
  queryEvalList
};
