/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";

const queryPunishList = data =>
  request({
    url: "/expandEval/queryPunishList.do",
    method: "post",
    data: data
  });

const getSchemeStateDict = data =>
  request({
    url: "/expandEval/getSchemeStateDict.do",
    method: "post",
    data: data
  });

const updateScheme = data =>
  request({
    url: "/expandEval/updateScheme.do",
    method: "post",
    data: data
  });

const insertScheme = data =>
  request({
    url: "/expandEval/insertScheme.do",
    method: "post",
    data: data
  });

const copyScheme = data =>
  request({
    url: "/expandEval/copyScheme.do",
    method: "post",
    data: data
  });

const processSchemeName = data =>
  request({
    url: "/expandEval/processSchemeName.do",
    method: "post",
    data: data
  });

const deleteSchemeById = data =>
  request({
    url: "/expandEval/deleteSchemeById.do",
    method: "post",
    data: data
  });

const startScheme = data =>
  request({
    url: "/expandEval/startScheme.do",
    method: "post",
    data: data
  });

const getEvalItemBeanBySchemeId = data =>
  request({
    url: "/expandEval/getEvalItemBeanBySchemeId.do",
    method: "post",
    data: data
  });

const saveExEveluateBean = data =>
  ajax({
    url: "/expandEval/saveExEveluateBean.do",
    method: "post",
    data: data
  });

const queryExpandEvalCategory = data =>
  request({
    url: "/expandEval/queryExpandEvalCategory.do",
    method: "post",
    data: data
  });
export default {
  queryPunishList,
  getSchemeStateDict,
  updateScheme,
  insertScheme,
  copyScheme,
  processSchemeName,
  deleteSchemeById,
  startScheme,
  getEvalItemBeanBySchemeId,
  saveExEveluateBean,
  queryExpandEvalCategory
};
