/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";

const getItemsTree = data =>
  request({
    url: "/scheme/getItemsTree.do",
    method: "post",
    data: data
  });

const processSchemeName = data =>
  request({
    url: "/scheme/processSchemeName.do",
    method: "post",
    data: data
  });

const insertScheme = data =>
  request({
    url: "/scheme/insertScheme.do",
    method: "post",
    data: data
  });

const copyScheme = data =>
  request({
    url: "/scheme/copyScheme.do",
    method: "post",
    data: data
  });

const deleteScheme = data =>
  request({
    url: "/scheme/deleteScheme.do",
    method: "post",
    data: data
  });

const querySchemeList = data =>
  request({
    url: "/scheme/querySchemeList.do",
    method: "post",
    data: data
  });

const savePunishItems = data =>
  ajax({
    url: "/scheme/savePunishItems.do",
    method: "post",
    data: data
  });

const saveEvalItems = data =>
  ajax({
    url: "/scheme/saveEvalItems.do",
    method: "post",
    data: data
  });

const saveCapacityItems = data =>
  ajax({
    url: "/scheme/saveCapacityItems.do",
    method: "post",
    data: data
  });

const saveInnovateItems = data =>
  ajax({
    url: "/scheme/saveInnovateItems.do",
    method: "post",
    data: data
  });

const getPunishItems = data =>
  request({
    url: "/scheme/getPunishItems.do",
    method: "post",
    data: data
  });
const getDictByDictNames = data =>
  request({
    url: "/systemConfApi/getDictByDictNames.do",
    method: "post",
    data: data
  });
const getEvalItems = data =>
  request({
    url: "/scheme/getEvalItems.do",
    method: "post",
    data: data
  });

const getCapacityItems = data =>
  request({
    url: "/scheme/getCapacityItems.do",
    method: "post",
    data: data
  });

const getInnovateItems = data =>
  request({
    url: "/scheme/getInnovateItems.do",
    method: "post",
    data: data
  });
const updateScheme = data =>
  request({
    url: "/scheme/updateScheme.do",
    method: "post",
    data: data
  });


const queryStuTypeByEducationLevelCode = data =>
  request({
    url: "/dOrg/queryStuTypeByEducationLevelCode.do",
    method: "post",
    data: data
  });



export default {
  queryStuTypeByEducationLevelCode,
  getDictByDictNames,
  getItemsTree,
  processSchemeName,
  updateScheme,
  insertScheme,
  copyScheme,
  deleteScheme,
  querySchemeList,
  savePunishItems,
  saveEvalItems,
  saveCapacityItems,
  saveInnovateItems,
  getPunishItems,
  getEvalItems,
  getCapacityItems,
  getInnovateItems
};
