/* Automatically generated by './build/runApi.js' */

import request from "~/utils/request";
import ajax from "~/utils/ajax";

const queryPunishList = data =>
  request({
    url: "/stuPunish/queryPunishList.do",
    method: "post",
    data: data
  });

const getPunishStateDict = data =>
  request({
    url: "/stuPunish/getPunishStateDict.do",
    method: "post",
    data: data
  });

const getPunishItemStateDict = data =>
  request({
    url: "/stuPunish/getPunishItemStateDict.do",
    method: "post",
    data: data
  });

const updatePunish = data =>
  request({
    url: "/stuPunish/updatePunish.do",
    method: "post",
    data: data
  });

const insertPunish = data =>
  request({
    url: "/stuPunish/insertPunish.do",
    method: "post",
    data: data
  });

const copyPunish = data =>
  request({
    url: "/stuPunish/copyPunish.do",
    method: "post",
    data: data
  });

const processPunishName = data =>
  request({
    url: "/stuPunish/processPunishName.do",
    method: "post",
    data: data
  });

const deletePunishById = data =>
  request({
    url: "/stuPunish/deletePunishById.do",
    method: "post",
    data: data
  });

const startPunish = data =>
  request({
    url: "/stuPunish/startPunish.do",
    method: "post",
    data: data
  });

const getPunishItemBeanByPunishId = data =>
  request({
    url: "/stuPunish/getPunishItemBeanByPunishId.do",
    method: "post",
    data: data
  });

const savePunishItemBean = data =>
  request({
    url: "/stuPunish/savePunishItemBean.do    (json请求)",
    method: "post",
    data: data
  });

const queryPunishItemByShoolYearId = data =>
  request({
    url: "/stuPunish/queryPunishItemByShoolYearId.do",
    method: "post",
    data: data
  });

const queryPunishRecordForStaff = data =>
  request({
    url: "/stuPunish/queryPunishRecordForStaff.do",
    method: "post",
    data: data
  });

const queryPunishRecordForStu = data =>
  request({
    url: "/stuPunish/queryPunishRecordForStu.do",
    method: "post",
    data: data
  });

const insertPunishRecord = data =>
  request({
    url: "/stuPunish/insertPunishRecord.do",
    method: "post",
    data: data
  });

const deletePunishRecord = data =>
  request({
    url: "/stuPunish/deletePunishRecord.do",
    method: "post",
    data: data
  });

const getPunshiRecordById = data =>
  request({
    url: "/stuPunish/getPunshiRecordById.do",
    method: "post",
    data: data
  });

const uploadStuPunish = data =>
  request({
    url: "/public/uploadStuPunish.do",
    method: "post",
    data: data
  });

const importPunishRecord = data =>
  request({
    url: "/stuPunish/importPunishRecord.do",
    method: "post",
    data: data
  });
export default {
  queryPunishList,
  getPunishStateDict,
  getPunishItemStateDict,
  updatePunish,
  insertPunish,
  copyPunish,
  processPunishName,
  deletePunishById,
  startPunish,
  getPunishItemBeanByPunishId,
  savePunishItemBean,
  queryPunishItemByShoolYearId,
  queryPunishRecordForStaff,
  queryPunishRecordForStu,
  insertPunishRecord,
  deletePunishRecord,
  getPunshiRecordById,
  uploadStuPunish,
  importPunishRecord
};
