/* Automatically generated by './build/make/*.js' */
import { mapGetters, mapActions } from "vuex";
import store from "../_store/index.js";

export default {
  data: function() {
    return {};
  },
  methods: {
    ...mapActions({
      queryMajorList: store.namespace + "/queryMajorList",
      insertOrg: store.namespace + "/insertOrg",
      getOrgTreeView: store.namespace + "/getOrgTreeView",
      updateOrg: store.namespace + "/updateOrg",
      deleteOrg: store.namespace + "/deleteOrg",
      getOrg: store.namespace + "/getOrg",
      getDictByDictNames: store.namespace + "/getDictByDictNames"
    })
  }
};
